-- MySQL Script generated by MySQL Workbench
-- Sat Aug 17 14:43:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_compraexplore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_compraexplore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_compraexplore` DEFAULT CHARACTER SET utf8 ;
USE `db_compraexplore` ;

-- -----------------------------------------------------
-- Table `db_compraexplore`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_compraexplore`.`CATEGORIA` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_compraexplore`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_compraexplore`.`PRODUCTOS` (
  `id_productos` INT NOT NULL AUTO_INCREMENT,
  `id_categoria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_productos`),
  INDEX `fk_PRODUCTOS_CATEGORIA1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTOS_CATEGORIA1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_compraexplore`.`CATEGORIA` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_compraexplore`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_compraexplore`.`CLIENTES` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_clientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_compraexplore`.`PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_compraexplore`.`PEDIDOS` (
  `id_pedidos` INT NOT NULL AUTO_INCREMENT,
  `id_clientes` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pedidos`),
  INDEX `fk_PEDIDOS_CLIENTES1_idx` (`id_clientes` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOS_CLIENTES1`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `db_compraexplore`.`CLIENTES` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_compraexplore`.`PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_compraexplore`.`PROVEEDOR` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_compraexplore`.`PROVEEDOR_PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_compraexplore`.`PROVEEDOR_PRODUCTOS` (
  `id_proveedor` INT NOT NULL,
  `id_productos` INT NOT NULL,
  INDEX `fk_proveedor_productos_idx` (`id_productos` ASC) VISIBLE,
  INDEX `fk_productos_proveedor_idx` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_productos`
    FOREIGN KEY (`id_productos`)
    REFERENCES `db_compraexplore`.`PRODUCTOS` (`id_productos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productos_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `db_compraexplore`.`PROVEEDOR` (`id_proveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_compraexplore`.`PRODUCTOS_PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_compraexplore`.`PRODUCTOS_PEDIDOS` (
  `id_producto` INT NOT NULL,
  `id_pedidos` INT NOT NULL,
  INDEX `fk_productos_pedidos_idx` (`id_pedidos` ASC) VISIBLE,
  INDEX `fk_pedidos_productos_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_productos_pedidos`
    FOREIGN KEY (`id_pedidos`)
    REFERENCES `db_compraexplore`.`PEDIDOS` (`id_pedidos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedidos_productos`
    FOREIGN KEY (`id_producto`)
    REFERENCES `db_compraexplore`.`PRODUCTOS` (`id_productos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
